version: '3'

services:
  backend:
    container_name: MVStudio-Backend
    build:
      context: ../MVStudio-Backend
    volumes:
      - static_volume:/MVStudio-Backend/static
      - ../MVStudio-Backend:/MVStudio-Backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - mvs
    restart: always
    command: >
      sh -c "sleep 5 &&
            python manage.py makemigrations &&
            python manage.py makemigrations member &&
            python manage.py makemigrations music_videos &&
            python manage.py migrate &&
            gunicorn --bind 0.0.0.0:8000 config.wsgi:application"

volumes:
  static_volume:


