# Generated by Django 5.0.6 on 2024-07-05 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("login_id", models.CharField(max_length=50, unique=True)),
                ("profile_image", models.CharField(max_length=2000, null=True)),
                ("comment", models.CharField(max_length=200, null=True)),
                ("nickname", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=200)),
                ("birthday", models.DateField()),
                ("sex", models.CharField(max_length=1)),
                ("youtube_account", models.CharField(max_length=200, null=True)),
                ("instagram_account", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "country",
                    models.ForeignKey(
                        db_column="country_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.country",
                    ),
                ),
            ],
        ),
    ]
